// ***********************************************************************
//
// Collection Interface
//
// ***********************************************************************
// Computer Science 102: Data Structures
// New York University, Fall 2013,
//
// Lecturers: Eric Koskinen and Daniel Schwartz-Narbonne
//
// (c) Copyright 1995, 2013, Oracle Corporation and/or its affiliates (Oracle).
// All rights reserved.
// http://docs.oracle.com/javase/tutorial/information/license.html
// ***********************************************************************

// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
// %%%%% DO NOT EDIT THIS FILE %%%%%
// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

public interface Collection<E> { //extends Iterable<E> {
    // Basic operations
    int size();
    boolean isEmpty();
    //boolean contains(E element);

    // Output operations
    String toString();
    void PrettyPrint();
}