// ***********************************************************************
//
// Queue Interface
//
// ***********************************************************************
// Computer Science 102: Data Structures
// New York University, Fall 2013,
//
// Lecturers: Eric Koskinen and Daniel Schwartz-Narbonne
//
// (c) Copyright 1995, 2013, Oracle Corporation and/or its affiliates (Oracle).
// All rights reserved.
// http://docs.oracle.com/javase/tutorial/information/license.html
// ***********************************************************************

// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
// %%%%% DO NOT EDIT THIS FILE %%%%%
// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

public interface Queue<E> extends Collection<E> {
    // Basic operations
    int size();
    void enqueue(E element);
    E dequeue() throws InvalidOperationException;    
    boolean isEmpty();

    // Output operations
    String toString();
    void PrettyPrint();
}